import React from 'react';
import Main from 'static/Main';
import Container from 'static/Container';
import P from 'static/Text';
import glamorous from 'glamorous';
import PropTypes from 'prop-types';

const AppMain = props => (
    <Main className={'main-stage'}>
        <Container className={'container'}>
            <P className={'paragraph'} justify>
                {'I am a paragraph that is generated by the main area of the app component. I have one big brother, App header and my little bro is the footer. Oh and a nephew too at some point, the sidebar'}
            </P>
        </Container>
    </Main>
);

export default AppMain;